sudo: false
language: node_js
node_js:
  - '6'
  - '4'
  - '0.12'
  - '0.10'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libstdc++-4.8-dev
before_install:
  - npm -g install npm@latest
  - export CXX="g++-4.8" CC="gcc-4.8"
